/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DankeRouteImport } from './routes/danke'
import { Route as IndexRouteImport } from './routes/index'

const DankeRoute = DankeRouteImport.update({
  id: '/danke',
  path: '/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/danke': typeof DankeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/danke': typeof DankeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/danke': typeof DankeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/danke'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/danke'
  id: '__root__' | '/' | '/danke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DankeRoute: typeof DankeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/danke': {
      id: '/danke'
      path: '/danke'
      fullPath: '/danke'
      preLoaderRoute: typeof DankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DankeRoute: DankeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
